1. Obtener el empleado con el sueldo mínimo.

SELECT NOM_EMP, APE_EMP, SUELD_EMP
FROM EMPLEADO
WHERE SUELD_EMP = (SELECT MIN(SUELD_EMP)
FROM EMPLEADO);




2. Listar empleados que ganan menos que el sueldo promedio.


SELECT  ID_EMP, NOM_EMP, APE_EMP, SUELD_EMP
FROM EMPLEADO
WHERE SUELD_EMP < (SELECT AVG(SUELD_EMP) FROM EMPLEADO)
ORDER BY SUELD_EMP;




3. Buscar el nombre del cargo del empleado con mayor sueldo.

SELECT NOM_CARGO, NOM_EMP, APE_EMP, SUELD_EMP
FROM EMPLEADO
JOIN CARGO 
ON CARGO_ID_CARGO = ID_CARGO
WHERE SUELD_EMP = (SELECT MAX(SUELD_EMP) FROM EMPLEADO);



4. Empleados que trabajan en los mismos departamentos que badulaque barraza.

SELECT NOM_EMP, APE_EMP, NOM_DPTO
FROM EMPLEADO
JOIN DEPARTAMENTO 
ON DEPARTAMENTO_ID_DPTO = ID_DPTO
WHERE DEPARTAMENTO_ID_DPTO = (SELECT DEPARTAMENTO_ID_DPTO FROM EMPLEADO
WHERE UPPER(NOM_EMP) = 'BADULAQUE'
AND UPPER(APE_EMP) = 'BARRAZA');
